project:
  type: website

website:
  title: "Kolachalama Docs"
  repo-url: https://github.com/vkola-lab/vkola-lab-docs
  repo-actions: [edit, issue, source]
  page-navigation: false # create prev/next links 
  reader-mode: false # enable reader mode toggle, hides the sideabars
  navbar:
    search: true
    # left:
      # - href: index.qmd
        # text: Home

  sidebar:
    style: "docked"
    search: true
    border: false
    # tools: # mini icons in sidebar
      # - icon: github
        # href: https://github.com/vkola-lab
      # - icon: youtube
        # href: https://www.youtube.com/@vijayakolachalama
    contents: auto

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    published-title: "Last Updated"
    date: last-modified

execute:
  freeze: auto
